task:
  name: Windows
  windows_container:
    dockerfile: docker/windows_vs_2019
    cpu: 4
    memory: 4G

  test_script:
    - dir c:\python
    - c:\python\python.exe --version

task:
  name: windows vm test

compute_engine_instance:
  image_project: windows-cloud
  image_family: windows-2019
  platform: windows

  sysinfo_script:
    - winver
