env:
  CIRRUS_LOG_TIMESTAMP: true
  GCP_PROJECT: pg-ci-images
  GCP_REPO: us-docker.pkg.dev/$GCP_PROJECT/ci


task:
  matrix:
    - name: test-linux-container-amd64
      container:
        image: $GCP_REPO/linux_debian_bullseye_ci:latest
    - name: test-linux-container-aarch64
      arm_container:
        image: $GCP_REPO/linux_debian_bullseye_ci:latest

  test_script:
    - id
    - uname -a
    - apt-get update && apt-get install -y curl procps
    - ulimit -a -H
    - ulimit -a -S
    - export
    - cat /proc/sys/kernel/core_pattern
    - sysctl kernel.core_pattern
    - sysctl kernel.core_pattern='/tmp/cores/%e-%s-%p.core' || true
    - cat /proc/sys/kernel/core_pattern
    #- curl ifconfig.me/all

  test_core:
    - ulimit -c unlimited
    - /usr/bin/sleep 3600 &
    - P=$!
    - echo $P
    - kill -SEGV $P
    - ls -l core*
    - ls -l /*core*


task:
  name: test-windows-container-base-amd64
  windows_container:
    image: $GCP_REPO/windows_ci_base:latest
  test_script:
    - set
    - ver
    - where perl
    - perl --version
    - python --version
    - curl ifconfig.me/all

task:
  name: test-windows-container-vs-2019-amd64
  windows_container:
    image: $GCP_REPO/windows_ci_vs_2019:latest
  test_script:
    - set
    - dir C:\BuildTools\VC\Auxiliary\Build
    - ver
    - where perl
    - perl --version
    - python --version
    - vcvarsall x64
    - bison --version
    - flex --version
    - curl ifconfig.me/all

#task:
#  name: Windows
#  windows_container:
#    dockerfile: docker/windows_vs_2019
#    cpu: 4
#    memory: 4G
#
#  test_script:
#    - cat c:/docker/install_perl.ps1
#
#task:
#  name: linux
#  container:
#    dockerfile: docker/linux
#
#  test_script:
#    - cat /docker/install_perl.ps1
