task:
  name: Windows
  windows_container:
    dockerfile: docker/windows_vs_2019
    cpu: 4
    memory: 4G

  test_script:
    - cat c:/docker/install_perl.ps1

task:
  name: linux
  container:
    dockerfile: docker/linux

  test_script:
    - cat /docker/install_perl.ps1
